apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        io.kompose.service: kafka-broker-1
      name: kafka-broker-1
    spec:
      ports:
        - name: "9092"
          port: 9092
          targetPort: 9092
      selector:
        io.kompose.service: kafka-broker-1
      type: LoadBalancer
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      name: zookeeper-service
      labels:
        app: zookeeper
    spec:
      ports:
        - port: 2181
          name: client
      selector:
        app: zookeeper
  -  apiVersion: apps/v1
     kind: StatefulSet
     metadata:
       name: kafka-broker-1
     spec:
       selector:
         matchLabels:
           app: kafka-broker-1
       serviceName: kafka-broker-1
       replicas: 1
       template:
         metadata:
           labels:
             app: kafka-broker-1
             io.kompose.service: kafka-broker-1
         spec:
           terminationGracePeriodSeconds: 10
           containers:
             - name: kafka-broker-1
               image: strimzi/kafka:0.18.0-kafka-2.5.0
               imagePullPolicy: IfNotPresent
               command: [ "/bin/sh" ]
               args: [ "-c", "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}" ]
               env:
                 - name: KAFKA_ADVERTISED_LISTENERS
                   value: "PLAINTEXT://kafka-broker-1:9092"
                 - name:  KAFKA_LISTENERS
                   value: "PLAINTEXT://0.0.0.0:9092"
                 - name: KAFKA_ZOOKEEPER_CONNECT
                   value: zookeeper-service:2181
               ports:
                 - containerPort: 9092
               resources: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: zookeeper
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: zookeeper
      template:
        metadata:
          labels:
            app: zookeeper
        spec:
          containers:
            - name: k8s-zookeeper
              image: quay.io/debezium/zookeeper
              ports:
                - containerPort: 2181
                  name: client
          restartPolicy: Always
        status: { }
kind: List
metadata: {}